### ISSUE TITLE
Django issue | Network Error

### ISSUE THREAD

**Issue by Sicks3c** [pawlaczyk/sarenka#31]
## Description

Hello Team

Thank you for making this tool
while following the instruction in `WSL Ubuntu 18.04` Machine
I managed to install all the requirements
but when I run the backend server I get this error 
```
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 396, in check
    databases=databases,
  File "/usr/local/lib/python3.6/dist-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.6/dist-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.6/dist-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.6/dist-packages/django/urls/resolvers.py", line 408, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.6/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/dist-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.6/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/dist-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/sarenka/sarenka/backend/backend/urls.py", line 28, in <module>
    path('vulns/', include("api_vulnerabilities.urls")),
  File "/usr/local/lib/python3.6/dist-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/sarenka/sarenka/backend/api_vulnerabilities/urls.py", line 2, in <module>
    from .views import CVESearchView, CWETop25, CWEData, CWEAllView, CVEDetailsAllView, CWEDetailsAllView, \
  File "/opt/sarenka/sarenka/backend/api_vulnerabilities/views.py", line 5, in <module>
    from .cve_and_cwe.cve_details_all import CVEDetailsAll
  File "/opt/sarenka/sarenka/backend/api_vulnerabilities/cve_and_cwe/cve_details_all.py", line 8, in <module>
    class CVEDetailsAll:
  File "/opt/sarenka/sarenka/backend/api_vulnerabilities/cve_and_cwe/cve_details_all.py", line 23, in CVEDetailsAll
    @lru_cache
  File "/usr/lib/python3.6/functools.py", line 477, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None
```

and the front end works fine
![3GSFPyw](https://i.imgur.com/3GSFPyw.png)

Giving a live `IP` Address results in `Network Error`

Best regards

**Comment by pawlaczyk** [comment]
Hi, 
thanks for message and details.

We are glad to hear that you like app!
We have just started wotking on fix, wchich is in api_vulnerabilities.

I will reply when solution will be done and tested on Ubuntu 18.04.

Best Regard

**Comment by pawlaczyk** [comment]
![ubuntu_18 04_fix](https://user-images.githubusercontent.com/16176980/104378082-b4c7a380-5527-11eb-883f-c5f565478f6f.PNG)

Hi, I just tested SARENKA on Ubuntu 18.04 with Python 3.8.7.
Please rebuild application with sarenka.py script.
Port has changed to :8000 (now you don't need to have Node.js.)
