### ISSUE TITLE
Trouble in process build !!

### ISSUE THREAD

**Issue by NetiSHTer22** [pawlaczyk/sarenka#75]
C:\Users\PC_NAME\sarenka>python3 sarenka\sarenka.py
!!! It is in develop mode !!!
Do you really want to build application?
Proceed (y/n): y
❤ Creating databases for Common Weakness Enumeration
❤ Removes folder with old databases for CWE ids
❤ Folder cwe database files in C:\Users\PC_NAME\sarenka\sarenka\backend\backend\cwe_databases for 'api_vulnerabilities' application created.
command:  python C:\Users\PC_NAME\sarenka\sarenka\backend\manage.py migrate api_vulnerabilities --database=cwe_none
python: can't open file 'C:\Users\PC_NAME': [Errno 2] No such file or directory
Traceback (most recent call last):
  File "sarenka\sarenka.py", line 293, in <module>
    sarenka_command.build()
  File "sarenka\sarenka.py", line 285, in build
    self.builder.run()
  File "sarenka\sarenka.py", line 266, in run
    self.__create_cwes_databases_files()
  File "sarenka\sarenka.py", line 219, in __create_cwes_databases_files
    self.helper.run_command(command)
  File "sarenka\sarenka.py", line 77, in run_command
    raise SarenkaBuildError(f"Error while executing command {command}")
__main__.SarenkaBuildError: Error while executing command python C:\Users\PC_NAME\sarenka\sarenka\backend\manage.py migrate api_vulnerabilities --database=cwe_none

C:\Users\PC_NAME\sarenka>

Can you help me ?

**Comment by bigverm23** [comment]
same issue today

**Comment by PhillMoran** [comment]
1. Make sure that sqlite is installed and in your path
2. There are 2 commands in sarenka.py that refer to 'python' either update them to python3 or other method you prefer... 
 search for python - you'll see them...
